insert into product_kashrut (ProductID, Kashrut) values (1, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (2, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (3, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (4, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (5, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (6, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (7, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (8, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (9, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (10, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (11, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (12, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (13, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (14, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (15, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (16, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (17, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (18, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (19, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (20, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (21, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (22, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (23, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (24, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (25, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (26, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (27, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (28, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (29, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (30, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (31, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (32, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (33, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (34, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (35, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (36, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (37, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (38, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (39, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (40, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (41, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (42, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (43, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (44, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (45, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (46, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (47, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (48, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (49, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (50, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (51, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (52, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (53, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (54, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (55, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (56, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (57, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (58, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (59, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (60, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (61, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (62, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (63, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (64, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (65, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (66, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (67, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (68, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (69, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (70, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (71, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (72, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (73, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (74, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (75, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (76, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (77, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (78, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (79, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (80, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (81, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (82, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (83, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (84, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (85, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (86, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (87, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (88, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (89, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (90, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (91, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (92, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (93, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (94, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (95, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (96, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (97, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (98, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (99, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (100, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (101, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (102, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (103, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (104, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (105, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (106, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (107, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (108, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (109, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (110, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (111, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (112, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (113, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (114, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (115, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (116, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (117, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (118, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (119, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (120, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (121, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (122, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (123, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (124, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (125, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (126, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (127, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (128, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (129, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (130, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (131, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (132, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (133, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (134, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (135, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (136, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (137, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (138, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (139, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (140, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (141, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (142, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (143, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (144, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (145, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (146, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (147, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (148, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (149, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (150, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (151, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (152, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (153, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (154, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (155, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (156, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (157, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (158, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (159, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (160, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (161, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (162, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (163, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (164, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (165, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (166, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (167, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (168, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (169, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (170, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (171, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (172, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (173, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (174, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (175, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (176, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (177, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (178, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (179, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (180, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (181, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (182, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (183, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (184, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (185, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (186, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (187, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (188, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (189, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (190, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (191, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (192, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (193, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (194, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (195, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (196, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (197, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (198, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (199, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (200, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (201, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (202, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (203, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (204, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (205, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (206, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (207, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (208, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (209, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (210, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (211, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (212, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (213, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (214, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (215, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (216, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (217, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (218, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (219, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (220, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (221, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (222, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (223, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (224, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (225, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (226, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (227, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (228, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (229, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (230, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (231, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (232, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (233, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (234, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (235, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (236, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (237, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (238, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (239, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (240, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (241, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (242, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (243, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (244, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (245, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (246, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (247, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (248, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (249, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (250, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (251, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (252, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (253, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (254, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (255, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (256, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (257, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (258, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (259, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (260, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (261, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (262, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (263, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (264, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (265, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (266, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (267, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (268, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (269, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (270, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (271, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (272, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (273, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (274, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (275, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (276, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (277, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (278, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (279, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (280, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (281, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (282, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (283, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (284, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (285, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (286, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (287, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (288, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (289, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (290, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (291, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (292, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (293, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (294, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (295, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (296, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (297, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (298, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (299, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (300, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (301, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (302, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (303, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (304, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (305, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (306, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (307, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (308, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (309, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (310, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (311, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (312, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (313, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (314, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (315, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (316, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (317, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (318, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (319, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (320, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (321, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (322, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (323, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (324, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (325, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (326, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (327, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (328, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (329, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (330, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (331, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (332, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (333, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (334, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (335, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (336, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (337, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (338, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (339, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (340, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (341, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (342, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (343, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (344, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (345, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (346, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (347, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (348, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (349, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (350, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (351, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (352, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (353, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (354, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (355, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (356, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (357, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (358, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (359, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (360, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (361, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (362, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (363, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (364, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (365, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (366, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (367, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (368, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (369, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (370, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (371, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (372, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (373, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (374, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (375, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (376, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (377, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (378, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (379, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (380, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (381, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (382, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (383, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (384, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (385, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (386, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (387, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (388, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (389, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (390, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (391, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (392, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (393, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (394, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (395, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (396, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (397, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (398, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (399, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (400, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (401, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (402, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (403, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (404, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (405, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (406, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (407, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (408, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (409, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (410, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (411, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (412, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (413, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (414, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (415, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (416, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (417, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (418, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (419, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (420, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (421, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (422, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (423, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (424, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (425, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (426, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (427, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (428, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (429, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (430, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (431, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (432, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (433, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (434, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (435, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (436, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (437, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (438, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (439, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (440, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (441, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (442, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (443, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (444, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (445, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (446, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (447, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (448, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (449, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (450, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (451, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (452, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (453, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (454, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (455, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (456, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (457, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (458, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (459, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (460, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (461, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (462, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (463, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (464, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (465, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (466, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (467, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (468, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (469, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (470, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (471, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (472, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (473, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (474, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (475, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (476, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (477, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (478, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (479, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (480, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (481, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (482, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (483, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (484, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (485, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (486, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (487, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (488, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (489, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (490, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (491, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (492, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (493, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (494, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (495, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (496, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (497, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (498, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (499, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (500, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (501, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (502, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (503, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (504, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (505, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (506, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (507, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (508, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (509, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (510, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (511, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (512, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (513, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (514, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (515, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (516, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (517, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (518, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (519, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (520, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (521, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (522, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (523, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (524, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (525, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (526, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (527, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (528, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (529, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (530, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (531, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (532, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (533, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (534, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (535, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (536, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (537, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (538, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (539, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (540, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (541, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (542, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (543, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (544, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (545, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (546, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (547, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (548, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (549, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (550, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (551, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (552, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (553, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (554, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (555, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (556, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (557, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (558, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (559, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (560, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (561, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (562, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (563, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (564, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (565, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (566, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (567, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (568, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (569, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (570, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (571, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (572, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (573, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (574, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (575, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (576, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (577, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (578, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (579, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (580, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (581, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (582, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (583, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (584, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (585, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (586, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (587, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (588, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (589, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (590, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (591, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (592, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (593, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (594, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (595, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (596, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (597, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (598, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (599, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (600, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (601, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (602, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (603, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (604, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (605, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (606, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (607, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (608, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (609, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (610, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (611, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (612, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (613, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (614, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (615, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (616, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (617, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (618, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (619, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (620, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (621, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (622, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (623, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (624, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (625, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (626, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (627, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (628, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (629, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (630, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (631, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (632, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (633, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (634, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (635, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (636, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (637, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (638, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (639, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (640, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (641, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (642, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (643, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (644, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (645, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (646, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (647, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (648, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (649, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (650, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (1, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (2, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (3, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (4, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (5, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (6, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (7, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (8, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (9, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (10, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (11, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (12, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (13, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (14, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (15, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (16, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (17, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (18, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (19, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (20, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (21, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (22, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (23, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (24, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (25, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (26, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (27, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (28, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (29, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (30, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (31, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (32, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (33, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (34, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (35, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (36, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (37, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (38, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (39, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (40, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (41, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (42, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (43, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (44, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (45, 'Jerusalem Rabbinate');
insert into product_kashrut (ProductID, Kashrut) values (46, 'Lameadrin');
insert into product_kashrut (ProductID, Kashrut) values (47, 'OU');
insert into product_kashrut (ProductID, Kashrut) values (48, 'Badatz Edah HaChareidit');
insert into product_kashrut (ProductID, Kashrut) values (49, 'Badatz Rav Mhpoud');
insert into product_kashrut (ProductID, Kashrut) values (50, 'Jerusalem Rabbinate');
